
#CONNECTING TO MONGODB DATABASE
spring.data.mongodb.host = localhost
spring.data.mongodb.port = 27017
spring.data.mongodb.database = Reddit

spring.mail.host=smtp.gmail.com
#spring.mail.port=465
spring.mail.port=587
spring.mail.username=shuklaraghav321@gmail.com
spring.mail.password=skiidztbentoayox
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
